CONFIG_PROSPECTOR_MODE_SCANNER=y
CONFIG_PROSPECTOR_DEFAULT_LAYOUT=2
CONFIG_PROSPECTOR_TOUCH_ENABLED=y
CONFIG_PROSPECTOR_MAX_LAYERS=6
CONFIG_PROSPECTOR_BATTERY_SUPPORT=n
CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=100
CONFIG_PROSPECTOR_SCANNER_MAIN_LOOP_INTERVAL_MS=100

# Required settings to make it compile and work
CONFIG_LV_Z_DOUBLE_VDB=y
CONFIG_LV_Z_VDB_SIZE=30
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_BAR=y
CONFIG_LV_USE_FLEX=y
CONFIG_LV_USE_ARC=y
CONFIG_LV_USE_CANVAS=y
CONFIG_LV_USE_IMAGE=y
CONFIG_LV_USE_SLIDER=y
CONFIG_LV_USE_SWITCH=y
CONFIG_LV_USE_BUTTON=y
CONFIG_LV_FONT_MONTSERRAT_12=y
CONFIG_LV_FONT_MONTSERRAT_16=y
CONFIG_LV_FONT_MONTSERRAT_18=y
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_28=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_20=y
CONFIG_LV_FONT_UNSCII_8=y
CONFIG_LV_FONT_UNSCII_16=y

CONFIG_PWM=y
CONFIG_LED=y
CONFIG_LED_PWM=y

CONFIG_LOG=n
